// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: x0 => globalThis.URL.revokeObjectURL(x0),
      _1294: x0 => x0.remove(),
      _1295: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _1296: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1297: x0 => globalThis.URL.createObjectURL(x0),
      _1298: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1298(f,arguments.length,x0) }),
      _1299: (x0,x1,x2,x3) => x0.toBlob(x1,x2,x3),
      _1300: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1300(f,arguments.length,x0) }),
      _1301: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1301(f,arguments.length,x0) }),
      _1302: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1302(f,arguments.length,x0) }),
      _1303: (x0,x1) => x0.querySelector(x1),
      _1304: (x0,x1) => x0.createElement(x1),
      _1305: (x0,x1) => x0.append(x1),
      _1306: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1307: (x0,x1) => x0.replaceChildren(x1),
      _1308: x0 => x0.click(),
      _1315: x0 => x0.toArray(),
      _1316: x0 => x0.toUint8Array(),
      _1317: x0 => ({serverTimestamps: x0}),
      _1319: x0 => ({merge: x0}),
      _1321: x0 => new firebase_firestore.FieldPath(x0),
      _1322: (x0,x1) => new firebase_firestore.FieldPath(x0,x1),
      _1323: (x0,x1,x2) => new firebase_firestore.FieldPath(x0,x1,x2),
      _1324: (x0,x1,x2,x3) => new firebase_firestore.FieldPath(x0,x1,x2,x3),
      _1325: (x0,x1,x2,x3,x4) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4),
      _1326: (x0,x1,x2,x3,x4,x5) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5),
      _1327: (x0,x1,x2,x3,x4,x5,x6) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6),
      _1328: (x0,x1,x2,x3,x4,x5,x6,x7) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7),
      _1329: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8),
      _1330: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _1331: () => globalThis.firebase_firestore.documentId(),
      _1332: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1333: x0 => globalThis.firebase_firestore.vector(x0),
      _1334: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1336: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1338: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1341: x0 => x0.call(),
      _1374: (x0,x1) => ({includeMetadataChanges: x0,source: x1}),
      _1375: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1375(f,arguments.length,x0) }),
      _1376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1376(f,arguments.length,x0) }),
      _1377: (x0,x1,x2,x3) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2,x3),
      _1378: (x0,x1,x2) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2),
      _1379: (x0,x1,x2) => globalThis.firebase_firestore.setDoc(x0,x1,x2),
      _1380: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1381: (x0,x1) => globalThis.firebase_firestore.query(x0,x1),
      _1385: x0 => globalThis.firebase_firestore.limit(x0),
      _1386: x0 => globalThis.firebase_firestore.limitToLast(x0),
      _1387: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1387(f,arguments.length,x0) }),
      _1388: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1388(f,arguments.length,x0) }),
      _1389: (x0,x1) => globalThis.firebase_firestore.orderBy(x0,x1),
      _1391: (x0,x1,x2) => globalThis.firebase_firestore.where(x0,x1,x2),
      _1393: x0 => globalThis.firebase_firestore.doc(x0),
      _1396: (x0,x1) => x0.data(x1),
      _1400: x0 => x0.docChanges(),
      _1409: () => globalThis.firebase_firestore.serverTimestamp(),
      _1417: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1419: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1420: (module,f) => finalizeWrapper(f, function() { return module.exports._1420(f,arguments.length) }),
      _1438: () => globalThis.firebase_firestore.or,
      _1439: () => globalThis.firebase_firestore.and,
      _1444: x0 => x0.path,
      _1447: () => globalThis.firebase_firestore.GeoPoint,
      _1448: x0 => x0.latitude,
      _1449: x0 => x0.longitude,
      _1451: () => globalThis.firebase_firestore.VectorValue,
      _1452: () => globalThis.firebase_firestore.Bytes,
      _1455: x0 => x0.type,
      _1457: x0 => x0.doc,
      _1459: x0 => x0.oldIndex,
      _1461: x0 => x0.newIndex,
      _1463: () => globalThis.firebase_firestore.DocumentReference,
      _1467: x0 => x0.path,
      _1476: x0 => x0.metadata,
      _1477: x0 => x0.ref,
      _1482: x0 => x0.docs,
      _1484: x0 => x0.metadata,
      _1488: () => globalThis.firebase_firestore.Timestamp,
      _1489: x0 => x0.seconds,
      _1490: x0 => x0.nanoseconds,
      _1526: x0 => x0.hasPendingWrites,
      _1528: x0 => x0.fromCache,
      _1540: () => globalThis.firebase_firestore.startAfter,
      _1541: () => globalThis.firebase_firestore.startAt,
      _1542: () => globalThis.firebase_firestore.endBefore,
      _1543: () => globalThis.firebase_firestore.endAt,
      _1547: x0 => x0.decode(),
      _1548: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1549: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1550: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1550(f,arguments.length,x0) }),
      _1551: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1551(f,arguments.length,x0) }),
      _1552: x0 => x0.send(),
      _1553: () => new XMLHttpRequest(),
      _1574: x0 => x0.toJSON(),
      _1575: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1575(f,arguments.length,x0) }),
      _1576: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1576(f,arguments.length,x0) }),
      _1577: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      _1578: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1578(f,arguments.length,x0) }),
      _1579: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1579(f,arguments.length,x0) }),
      _1580: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1580(f,arguments.length,x0) }),
      _1581: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1581(f,arguments.length,x0) }),
      _1582: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      _1586: (x0,x1,x2) => globalThis.firebase_auth.createUserWithEmailAndPassword(x0,x1,x2),
      _1596: (x0,x1,x2) => globalThis.firebase_auth.signInWithEmailAndPassword(x0,x1,x2),
      _1601: x0 => x0.signOut(),
      _1602: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      _1625: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      _1640: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      _1641: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      _1642: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      _1648: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      _1663: () => globalThis.firebase_auth.debugErrorMap,
      _1666: () => globalThis.firebase_auth.browserSessionPersistence,
      _1668: () => globalThis.firebase_auth.browserLocalPersistence,
      _1670: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      _1673: x0 => globalThis.firebase_auth.multiFactor(x0),
      _1674: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      _1676: x0 => x0.currentUser,
      _1690: x0 => x0.displayName,
      _1691: x0 => x0.email,
      _1692: x0 => x0.phoneNumber,
      _1693: x0 => x0.photoURL,
      _1694: x0 => x0.providerId,
      _1695: x0 => x0.uid,
      _1696: x0 => x0.emailVerified,
      _1697: x0 => x0.isAnonymous,
      _1698: x0 => x0.providerData,
      _1699: x0 => x0.refreshToken,
      _1700: x0 => x0.tenantId,
      _1701: x0 => x0.metadata,
      _1703: x0 => x0.providerId,
      _1704: x0 => x0.signInMethod,
      _1705: x0 => x0.accessToken,
      _1706: x0 => x0.idToken,
      _1707: x0 => x0.secret,
      _1718: x0 => x0.creationTime,
      _1719: x0 => x0.lastSignInTime,
      _1724: x0 => x0.code,
      _1726: x0 => x0.message,
      _1738: x0 => x0.email,
      _1739: x0 => x0.phoneNumber,
      _1740: x0 => x0.tenantId,
      _1763: x0 => x0.user,
      _1766: x0 => x0.providerId,
      _1767: x0 => x0.profile,
      _1768: x0 => x0.username,
      _1769: x0 => x0.isNewUser,
      _1772: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      _1777: x0 => x0.displayName,
      _1778: x0 => x0.enrollmentTime,
      _1779: x0 => x0.factorId,
      _1780: x0 => x0.uid,
      _1782: x0 => x0.hints,
      _1783: x0 => x0.session,
      _1785: x0 => x0.phoneNumber,
      _1797: (x0,x1) => x0.getItem(x1),
      _1802: (x0,x1) => x0.appendChild(x1),
      _1804: (x0,x1) => x0.removeItem(x1),
      _1805: (x0,x1,x2) => x0.setItem(x1,x2),
      _1824: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1825: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1826: x0 => globalThis.firebase_core.getApp(x0),
      _1827: () => globalThis.firebase_core.getApp(),
      _1828: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1925: () => globalThis.firebase_core.SDK_VERSION,
      _1931: x0 => x0.apiKey,
      _1933: x0 => x0.authDomain,
      _1935: x0 => x0.databaseURL,
      _1937: x0 => x0.projectId,
      _1939: x0 => x0.storageBucket,
      _1941: x0 => x0.messagingSenderId,
      _1943: x0 => x0.measurementId,
      _1945: x0 => x0.appId,
      _1947: x0 => x0.name,
      _1948: x0 => x0.options,
      _1949: (x0,x1) => x0.debug(x1),
      _1950: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1950(f,arguments.length,x0) }),
      _1951: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1951(f,arguments.length,x0,x1) }),
      _1952: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1953: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1954: (x0,x1) => x0.createScriptURL(x1),
      _1955: (x0,x1,x2) => x0.createScript(x1,x2),
      _1956: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1956(f,arguments.length,x0) }),
      _1958: Date.now,
      _1960: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1961: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1962: () => new Error().stack,
      _1963: () => typeof dartUseDateNowForTicks !== "undefined",
      _1964: () => 1000 * performance.now(),
      _1965: () => Date.now(),
      _1966: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1967: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1968: () => new WeakMap(),
      _1969: (map, o) => map.get(o),
      _1970: (map, o, v) => map.set(o, v),
      _1971: (exn) => exn.toString(),
      _1972: (exn) => exn.stack,
      _1973: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1974: x0 => new WeakRef(x0),
      _1975: x0 => x0.deref(),
      _1982: () => globalThis.WeakRef,
      _1985: s => JSON.stringify(s),
      _1986: s => printToConsole(s),
      _1987: (o, p, r) => o.replaceAll(p, () => r),
      _1988: (o, p, r) => o.replace(p, () => r),
      _1989: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1990: s => s.toUpperCase(),
      _1991: s => s.trim(),
      _1992: s => s.trimLeft(),
      _1993: s => s.trimRight(),
      _1994: (string, times) => string.repeat(times),
      _1995: Function.prototype.call.bind(String.prototype.indexOf),
      _1996: (s, p, i) => s.lastIndexOf(p, i),
      _1997: (string, token) => string.split(token),
      _1998: Object.is,
      _2002: (o, c) => o instanceof c,
      _2003: o => Object.keys(o),
      _2033: x0 => new Array(x0),
      _2035: x0 => x0.length,
      _2037: (x0,x1) => x0[x1],
      _2038: (x0,x1,x2) => { x0[x1] = x2 },
      _2041: (x0,x1,x2) => new DataView(x0,x1,x2),
      _2043: x0 => new Int8Array(x0),
      _2044: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _2046: x0 => new Uint8ClampedArray(x0),
      _2048: x0 => new Int16Array(x0),
      _2050: x0 => new Uint16Array(x0),
      _2052: x0 => new Int32Array(x0),
      _2054: x0 => new Uint32Array(x0),
      _2056: x0 => new Float32Array(x0),
      _2058: x0 => new Float64Array(x0),
      _2082: x0 => x0.random(),
      _2085: () => globalThis.Math,
      _2098: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _2099: (handle) => clearTimeout(handle),
      _2100: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _2101: (handle) => clearInterval(handle),
      _2102: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _2103: () => Date.now(),
      _2104: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _2105: (x0,x1) => x0.exec(x1),
      _2106: (x0,x1) => x0.test(x1),
      _2107: x0 => x0.pop(),
      _2109: o => o === undefined,
      _2111: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _2113: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _2114: o => o instanceof RegExp,
      _2115: (l, r) => l === r,
      _2116: o => o,
      _2117: o => o,
      _2118: o => o,
      _2119: b => !!b,
      _2120: o => o.length,
      _2122: (o, i) => o[i],
      _2123: f => f.dartFunction,
      _2124: () => ({}),
      _2125: () => [],
      _2127: () => globalThis,
      _2128: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _2130: (o, p) => o[p],
      _2131: (o, p, v) => o[p] = v,
      _2132: (o, m, a) => o[m].apply(o, a),
      _2134: o => String(o),
      _2135: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _2136: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2136(f,arguments.length,x0) }),
      _2137: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2137(f,arguments.length,x0,x1) }),
      _2138: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _2139: o => [o],
      _2140: (o0, o1) => [o0, o1],
      _2141: (o0, o1, o2) => [o0, o1, o2],
      _2142: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _2143: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2144: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2147: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2148: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2149: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2150: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2151: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2152: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2153: x0 => new ArrayBuffer(x0),
      _2154: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _2156: x0 => x0.index,
      _2158: x0 => x0.flags,
      _2159: x0 => x0.multiline,
      _2160: x0 => x0.ignoreCase,
      _2161: x0 => x0.unicode,
      _2162: x0 => x0.dotAll,
      _2163: (x0,x1) => { x0.lastIndex = x1 },
      _2164: (o, p) => p in o,
      _2165: (o, p) => o[p],
      _2166: (o, p, v) => o[p] = v,
      _2167: (o, p) => delete o[p],
      _2168: () => new XMLHttpRequest(),
      _2169: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _2173: x0 => x0.send(),
      _2175: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2175(f,arguments.length,x0) }),
      _2176: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2176(f,arguments.length,x0) }),
      _2177: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _2178: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _2190: () => new FileReader(),
      _2191: (x0,x1) => x0.readAsArrayBuffer(x1),
      _2192: () => new AbortController(),
      _2193: x0 => x0.abort(),
      _2194: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2195: (x0,x1) => globalThis.fetch(x0,x1),
      _2196: (x0,x1) => x0.get(x1),
      _2197: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2197(f,arguments.length,x0,x1,x2) }),
      _2198: (x0,x1) => x0.forEach(x1),
      _2199: x0 => x0.getReader(),
      _2200: x0 => x0.cancel(),
      _2201: x0 => x0.read(),
      _2202: (x0,x1) => x0.key(x1),
      _2203: (x0,x1) => x0.item(x1),
      _2204: x0 => x0.trustedTypes,
      _2205: (x0,x1) => { x0.text = x1 },
      _2206: o => o instanceof Array,
      _2211: a => a.pop(),
      _2212: (a, i) => a.splice(i, 1),
      _2214: (a, s, e) => a.slice(s, e),
      _2216: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2217: a => a.length,
      _2219: (a, i) => a[i],
      _2220: (a, i, v) => a[i] = v,
      _2222: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2223: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2225: o => o instanceof Uint8Array,
      _2226: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2227: o => o instanceof Int8Array,
      _2228: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2229: o => o instanceof Uint8ClampedArray,
      _2230: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2231: o => o instanceof Uint16Array,
      _2232: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2233: o => o instanceof Int16Array,
      _2234: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2235: o => o instanceof Uint32Array,
      _2236: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2237: o => o instanceof Int32Array,
      _2238: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2240: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2241: o => o instanceof Float32Array,
      _2242: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2243: o => o instanceof Float64Array,
      _2244: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2245: (t, s) => t.set(s),
      _2247: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2249: o => o.buffer,
      _2250: o => o.byteOffset,
      _2251: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2252: (b, o) => new DataView(b, o),
      _2253: (b, o, l) => new DataView(b, o, l),
      _2254: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2255: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2256: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2257: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2258: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2259: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2260: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2261: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2262: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2263: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2264: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2265: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2268: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2269: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2270: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2271: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2272: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2273: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2274: Function.prototype.call.bind(Number.prototype.toString),
      _2275: Function.prototype.call.bind(BigInt.prototype.toString),
      _2276: Function.prototype.call.bind(Number.prototype.toString),
      _2277: (d, digits) => d.toFixed(digits),
      _2283: (x0,x1) => x0.getContext(x1),
      _2289: () => globalThis.document,
      _2295: (x0,x1) => { x0.height = x1 },
      _2297: (x0,x1) => { x0.width = x1 },
      _2299: (x0,x1) => { x0.pointerEvents = x1 },
      _2308: x0 => x0.style,
      _2311: x0 => x0.src,
      _2312: (x0,x1) => { x0.src = x1 },
      _2313: x0 => x0.naturalWidth,
      _2314: x0 => x0.naturalHeight,
      _2330: x0 => x0.status,
      _2331: (x0,x1) => { x0.responseType = x1 },
      _2333: x0 => x0.response,
      _2382: (x0,x1) => { x0.responseType = x1 },
      _2383: x0 => x0.response,
      _2472: (x0,x1) => { x0.oncancel = x1 },
      _2478: (x0,x1) => { x0.onchange = x1 },
      _2518: (x0,x1) => { x0.onerror = x1 },
      _2891: (x0,x1) => { x0.src = x1 },
      _2902: x0 => x0.width,
      _2904: x0 => x0.height,
      _3388: (x0,x1) => { x0.accept = x1 },
      _3402: x0 => x0.files,
      _3428: (x0,x1) => { x0.multiple = x1 },
      _3446: (x0,x1) => { x0.type = x1 },
      _3698: (x0,x1) => { x0.type = x1 },
      _3706: (x0,x1) => { x0.crossOrigin = x1 },
      _3708: (x0,x1) => { x0.text = x1 },
      _3740: x0 => x0.width,
      _3741: (x0,x1) => { x0.width = x1 },
      _3742: x0 => x0.height,
      _3743: (x0,x1) => { x0.height = x1 },
      _4164: () => globalThis.window,
      _4205: x0 => x0.document,
      _4208: x0 => x0.location,
      _4227: x0 => x0.navigator,
      _4489: x0 => x0.trustedTypes,
      _4490: x0 => x0.sessionStorage,
      _4491: x0 => x0.localStorage,
      _4506: x0 => x0.hostname,
      _4617: x0 => x0.vendor,
      _4824: x0 => x0.length,
      _6728: x0 => x0.type,
      _6729: x0 => x0.target,
      _6769: x0 => x0.signal,
      _6824: x0 => x0.baseURI,
      _6841: () => globalThis.document,
      _6922: x0 => x0.body,
      _6924: x0 => x0.head,
      _7256: (x0,x1) => { x0.id = x1 },
      _8602: x0 => x0.value,
      _8604: x0 => x0.done,
      _8784: x0 => x0.size,
      _8785: x0 => x0.type,
      _8792: x0 => x0.name,
      _8793: x0 => x0.lastModified,
      _8798: x0 => x0.length,
      _8804: x0 => x0.result,
      _9301: x0 => x0.url,
      _9303: x0 => x0.status,
      _9305: x0 => x0.statusText,
      _9306: x0 => x0.headers,
      _9307: x0 => x0.body,
      _12935: x0 => x0.name,
      _13651: () => globalThis.console,
      _13702: x0 => x0.name,
      _13703: x0 => x0.message,
      _13704: x0 => x0.code,
      _13706: x0 => x0.customData,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
