// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgIbZomBc5D5JKzUSGSFNk7QiQ6vqbVc',
    appId: '1:447290665864:web:e66366f67f1465dae4e83d',
    messagingSenderId: '447290665864',
    projectId: 'pingcv',
    authDomain: 'pingcv.firebaseapp.com',
    storageBucket: 'pingcv.firebasestorage.app',
    measurementId: 'G-8RVL0TMEM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywsF3hqGFWH8odIv7tNx6OO04Z_-bsac',
    appId: '1:447290665864:android:092edb0412b43b73e4e83d',
    messagingSenderId: '447290665864',
    projectId: 'pingcv',
    storageBucket: 'pingcv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_B_9jGcbMeZ2gDcg1ItJDaP8-4YyEsM',
    appId: '1:447290665864:ios:b6f25af59bfb737be4e83d',
    messagingSenderId: '447290665864',
    projectId: 'pingcv',
    storageBucket: 'pingcv.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_B_9jGcbMeZ2gDcg1ItJDaP8-4YyEsM',
    appId: '1:447290665864:ios:b6f25af59bfb737be4e83d',
    messagingSenderId: '447290665864',
    projectId: 'pingcv',
    storageBucket: 'pingcv.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvgIbZomBc5D5JKzUSGSFNk7QiQ6vqbVc',
    appId: '1:447290665864:web:5ec96a652781dfe5e4e83d',
    messagingSenderId: '447290665864',
    projectId: 'pingcv',
    authDomain: 'pingcv.firebaseapp.com',
    storageBucket: 'pingcv.firebasestorage.app',
    measurementId: 'G-V5G2PS9RW5',
  );
}
